In [5]:
import numpy as np

In [23]:
arr=np.arange(0,11)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr[8]

8

In [29]:
arr[1:5]

array([1, 2, 3, 4])

In [34]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [36]:
arr[:5]

array([0, 1, 2, 3, 4])

In [38]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
arr[0:5]=100

In [42]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [50]:
arr=np.arange(0,11)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
slice_of_arr=arr[0:5]

In [64]:
slice_of_arr[:]=99

In [66]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [68]:
arr_new=arr.copy()

In [70]:
arr_new

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [72]:
arr_2d=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [74]:
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [76]:
arr_2d.shape

(3, 3)

In [80]:
arr_2d[2]

array([70, 80, 90])

In [82]:
arr_2d[1:2]

array([[40, 50, 60]])

In [90]:
arr=np.arange(1,11)

In [96]:
bool_arr= arr>4

In [98]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [100]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [102]:
arr[arr<4]

array([1, 2, 3])