In [1]:
import numpy as np

In [2]:
mylist=[1,2,3]

In [3]:
type(mylist)

list

In [5]:
myarr=np.array(mylist)

In [6]:
myarr

array([1, 2, 3])

In [7]:
type(myarr)

numpy.ndarray

In [8]:
my_matrix=[[1,2,3],[4,5,6]]

In [9]:
my_matrix

[[1, 2, 3], [4, 5, 6]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.linspace(0,10,39)

array([ 0.        ,  0.26315789,  0.52631579,  0.78947368,  1.05263158,
        1.31578947,  1.57894737,  1.84210526,  2.10526316,  2.36842105,
        2.63157895,  2.89473684,  3.15789474,  3.42105263,  3.68421053,
        3.94736842,  4.21052632,  4.47368421,  4.73684211,  5.        ,
        5.26315789,  5.52631579,  5.78947368,  6.05263158,  6.31578947,
        6.57894737,  6.84210526,  7.10526316,  7.36842105,  7.63157895,
        7.89473684,  8.15789474,  8.42105263,  8.68421053,  8.94736842,
        9.21052632,  9.47368421,  9.73684211, 10.        ])

In [20]:
np.eye(6) #idetity matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(100)

array([0.29899683, 0.36458469, 0.00129237, 0.59582795, 0.5111608 ,
       0.13512443, 0.85612783, 0.47537456, 0.9462075 , 0.68768605,
       0.88699844, 0.30915293, 0.37604398, 0.45515207, 0.34062381,
       0.85502911, 0.95407033, 0.07055621, 0.84738725, 0.11332195,
       0.7991056 , 0.36056522, 0.16736362, 0.73496984, 0.17810841,
       0.7204066 , 0.05245591, 0.19510119, 0.26368169, 0.89672575,
       0.61310735, 0.9722364 , 0.84123436, 0.07400813, 0.50196454,
       0.69248416, 0.59123925, 0.5450137 , 0.33461194, 0.09249107,
       0.6722927 , 0.72846466, 0.58758027, 0.00777315, 0.20684991,
       0.61493706, 0.44486647, 0.89055263, 0.87869674, 0.69648593,
       0.78508204, 0.57894057, 0.92593623, 0.74817892, 0.90820713,
       0.98546144, 0.09971405, 0.2469958 , 0.14843701, 0.4468204 ,
       0.69531227, 0.0521917 , 0.4606162 , 0.58454423, 0.61660896,
       0.79855266, 0.67223986, 0.18445622, 0.67211394, 0.86737168,
       0.88593299, 0.76197445, 0.40613839, 0.08330317, 0.70761

In [22]:
np.random.rand(5,2)

array([[0.57183377, 0.48527827],
       [0.27799348, 0.87896318],
       [0.67206687, 0.70168609],
       [0.52452414, 0.06584018],
       [0.25437324, 0.66435661]])

In [23]:
np.random.randn(10)

array([ 0.61127391,  0.04424891, -0.6191287 , -0.06549449,  0.47521674,
       -0.15263509,  1.02388091, -0.06174478,  2.13219658,  0.65517301])

In [26]:
np.random.randint(1,100,(10,10))

array([[35, 82, 10, 13, 10,  8, 80, 35, 49, 18],
       [98, 22, 35, 29, 55,  5, 44, 44,  8, 15],
       [ 8, 25, 38,  2, 97, 31, 63, 42, 22, 16],
       [18, 51, 17, 99, 40, 44, 53, 25, 38,  1],
       [33,  1, 15,  8, 86, 97, 56, 29, 87, 34],
       [63,  2, 20, 51, 72, 28, 71,  7, 98, 32],
       [34, 32, 13, 76, 58, 48, 88, 50,  5, 70],
       [16, 98,  9, 27, 48, 84, 41, 83, 11,  3],
       [ 9,  1,  2, 72, 62, 51, 48, 52,  5, 27],
       [56, 88, 27, 47,  2, 38, 23, 92, 56, 79]])

In [27]:
np.random.seed(42)

In [36]:
arr=np.arange(0,25)

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr.max()

24

In [38]:
arr.argmax()

24

In [39]:
ranrr=np.random.randint(0,10,3)

In [40]:
ranrr

array([6, 3, 7])

In [42]:
ranrr.reshape(1,3)

array([[6, 3, 7]])

In [43]:
ranrr.argmax()

2

In [44]:
ranrr.dtype

dtype('int32')